---
- name: Playbook for sec group
  hosts: localhost
  gather_facts: no
    - name:Check host
      ping:

- name: Run Private Playbook
  Include: private_subnets.yaml

- name: Run Public Playbook
  Include: public_subnets.yml

- name: Run Sec Group
  include: sec_group.yaml


- name: Create VPC
  include: vpc.yaml

- name: Add igw
  import_playbook: igw.yaml

- name: Add Public RT
  import_playbook: rt_public.yaml

- name: Add private RT
  import_playbook: rt_private.yaml


