---
- name: Playbook for sec group
  hosts: localhost
  gather_facts: no
  tasks: 
    - name: create launch config
      ec2_lc:
        name: my_new_lc
        image_id: ami-02eac2c0129f6376b
        key_name: mykey
        region: us-east-1
        security_groups: sg-23423
        instance_type: m1.small
        assign_public_ip: yes
-name: ASG
 ec2_asg:
   name: myasg
   launch_config_name: my_new_lc
   health_check_period: 60
   health_check_type: ELB
   replace_all_instances: yes
   min_size: 3
   max_size: 48
   desired_capacity: 3
   vpc_zone_
   region: us-east-1