---
- name: Playbook for sec group
  hosts: localhost
  gather_facts: no
  tasks: 
    - local_action:
        module: ec2_elb_lb
        name: "NewELB"
        state: present
        region: us-east-
        listeners:
            - protocol: http
              load_balancer_port: 80
              instance_port: 80
              tags:
                Name: "NewELB"
                stack: "production"
                client: "Bob" 