---
- name: Playbook for VPC
  hosts: localhost
  tasks:
    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: us-east-1
        filters:
          "tag:Task": VPC
      register: VPC1


- name: Create 