---
- name: Playbook for sec group
  hosts: localhost
  tasks:
   gather_facts: no
  - name: Create  private subnet1
    ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      cidr: 10.0.1.0/24
      resource_tags:
        Name: Database Subnet1
    register: database_subnet2

    - name: Create  private subnet2
    ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      cidr: 10.0.1.0/24
      resource_tags:
        Name: Database Subnet2
    register: database_subnet2

    - name: Create  private subnet3
    ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      cidr: 10.0.1.0/24
      resource_tags:
        Name: Database Subnet3
    register: database_subnet3