---
- name: Playbook for sec group
  hosts: localhost
  tasks:
   gather_facts: no
  - name: Create  private subnet1
    ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      region: us-east-1
      cidr: 10.0.1.0/24
      resource_tags:
        Name: Web_Subnet1
    register: Web_subnet2

    - name: Create  private subnet2
    ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      cidr: 10.0.1.0/24
      resource_tags:
        Name: Web_Subnet2
    register: Web_subnet2

    - name: Create  private subnet3
    ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      cidr: 10.0.1.0/24
      resource_tags:
        Name: Web_Subnet3
    register: Web_subnet3