---
- name: Playbook for sec group
  hosts: localhost
  tasks:
   gather_facts: no
    - name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: vpc-1245678
    region: us-west-1
    tags:
      Name: Public
    subnets:
      - subnet-3c34d132
      - subnet-67fc8b59
      - subnet-69d4f835

    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_route_table
    