
---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: present
      with_items: 
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysql
        - php-pdo
        - php-gd
        - php-mbstring
        - unzip
        - rpm
    - name: start apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: start mariadb
      systemd:  
        name: httpd
        state: restarted
        enabled: yes


    - name: updatee php
      shell: "yum -y install epel-release" 
    - name: a  
      shell: "rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    - name: b    
      shell: "yum -y install yum-utils"
    - name: b        
      shell: "yum-config-manager --enable remi-php70"
    - name: c   
      shell: "yum update -y"
    - name: d  
      shell: "systemctl restart httpd"

    
    
   ---
- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
  become: yes