---
- name: playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks: 
     - name: install multiple package
       package:
         name: "{{item}}"
         state: present
       with_items:   
         - telnet
         - lftp
         - firewalld
         - curl
         - gzip
         - httpd
         - sshd
