---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create repo
      copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/


  - name: Install agent
    package:
      name: resverbackup-enterprise-agent
      state: present
    

  - name: Get key
    shell: "r1soft-setup --get-key "http://52.212.150.163:8080"
