---
- name: playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks: 
     - name: install multiple user
       user:
         name: "{{item}}"
         state: present
       with_items:   
         - murat
         - ulan
         - max
         - sera 
         - mahsuda
         - ali
         - enver
         - talant
         - mika
         - anara
  host: all       
  name: Create ssh public key
    task:
      name: create public ssh key for each user
      cp: pub-key to this "{{hosts}}"
      fetch: pull public-keys 
      put: /home/mahsuda/hosts-public-keys

    

         
