---
- name: playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks: 
     - name: install multiple user
       user:
         name: "{{item}}"
         state: present
       with_items:   
         - bob
         - sam
         - ben
         - tim 
