---
- name: Playbook for Stopping Services
  hosts: "{{hosts}}"
  become: yes
  become_method: sudo
  tasks:
   - name: register
      shell: uname -r
      register: message

    - name: Debug
      debug:
        msg: "{{message}}"
    - name: upgrade kernel
      package:
        name: kernel
        state: latest

    - name: Reboot
      shell: "shutdown -r now"

    - name: Pause 
      pause: 
        minutes: 5 
